language: php
php:
  - 5.6
  - 7.0
  - 7.2
  - 7.1
  - 7.3

install:
  - composer self-update
  - composer install --prefer-source --no-interaction

before_script:
  - composer require atoum/atoum
script:
  - vendor/bin/atoum -d tests/units/

branches:
  only:
  - master
